# -*- coding: utf-8 -*-
"""planner_mode.government_report_generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mQwiDSJxA_qF_j7HLvNGgJpQ3cZWPriq
"""

import pandas as pd
import numpy as np
import json

df=pd.read_csv("C:\hackathon_projects\data\simulation_mode_hotspots_overall.csv")

if "simulated_risk_level" not in df.columns:
    low_thresh = df["simulated_risk_score"].quantile(0.33)
    high_thresh = df["simulated_risk_score"].quantile(0.66)

    conditions = [
        df["simulated_risk_score"] < low_thresh,
        (df["simulated_risk_score"] >= low_thresh) & (df["simulated_risk_score"] < high_thresh),
        df["simulated_risk_score"] >= high_thresh
    ]
    levels = ["Low", "Medium", "High"]
    df["simulated_risk_level"] = np.select(conditions, levels, default="Low")

# --- Generate risk level summary for the report ---
risk_summary = df["simulated_risk_level"].value_counts().reset_index()
risk_summary.columns = ["Risk Level", "Count"]
risk_summary.to_csv("government_risk_level_summary.csv", index=False)
print("✅ Risk level summary saved.")

# --- Top 20 overall hotspots for reporting ---
top_hotspots = (
    df.groupby(['latitude', 'longitude'])['simulated_risk_score']
    .mean()
    .reset_index()
    .sort_values(by='simulated_risk_score', ascending=False)
    .head(20)
)
top_hotspots.to_csv("government_top_hotspots_overall.csv", index=False)
print("✅ Top 20 overall hotspots saved.")

# --- Optional: Top 20 hourly hotspots for temporal insights ---
if 'hour_of_day' in df.columns:
    top_hourly_hotspots = (
        df.groupby(['latitude', 'longitude', 'hour_of_day'])['simulated_risk_score']
        .mean()
        .reset_index()
        .sort_values(by='simulated_risk_score', ascending=False)
        .head(20)
    )
    top_hourly_hotspots.to_csv("government_top_hotspots_hourly.csv", index=False)
    print("✅ Top 20 hourly hotspots saved.")

# --- Optional: Quick preview for verification ---
print("\nRisk Level Summary:\n", risk_summary)
print("\nTop 5 Overall Hotspots:\n", top_hotspots.head())

low_thresh = df["simulated_risk_score"].quantile(0.33)
high_thresh = df["simulated_risk_score"].quantile(0.66)

def classify_risk(score):
    if score <= low_thresh:
        return "Low"
    elif score <= high_thresh:
        return "Medium"
    else:
        return "High"

df["simulated_risk_level"] = df["simulated_risk_score"].apply(classify_risk)

risk_distribution = df['simulated_risk_level'].value_counts().reset_index()
risk_distribution.columns = ['simulated_risk_level', 'count']
risk_distribution.to_csv("government_risk_distribution.csv", index=False)

risk_distribution

df.to_csv("government_simulation_report.csv", index=False)

print("Government report datasets generated successfully!")



