# -*- coding: utf-8 -*-
"""planner_mode.time_based_risk_planning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VFcJh63xPv3_JhN4I6M3H0RTHgvinlZ1
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("C:\hackathon_projects\data\predictive_layer_with_level.csv")

# Calculate average risk by hour
time_risk = df.groupby("hour_of_day")["predicted_risk_score"].mean().reset_index()
time_risk.columns = ["hour_of_day", "average_risk"]
time_risk.to_csv("planner_time_risk.csv", index=False)

# Peak hours
peak_hour = time_risk.loc[time_risk["average_risk"].idxmax(), "hour_of_day"]
print("Peak risk hour:", peak_hour)

plt.figure(figsize=(10,5))
plt.plot(time_risk['hour_of_day'], time_risk['average_risk'], marker='o')
plt.title("Average Predicted Risk by Hour")
plt.xlabel("Hour of Day")
plt.ylabel("Average Risk Score")
plt.grid(True)
plt.xticks(range(0,24))
plt.show()

high_risk_hours = time_risk[time_risk["average_risk"] > 70]["hour_of_day"].tolist()
print("High-risk hours:", high_risk_hours)

