# -*- coding: utf-8 -*-
"""planner_mode.Simulation_Mode

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1R2EQ2DhZDtOeYs4u_Sz7BeFe8n2chW
"""

import pandas as pd
import numpy as np

df=pd.read_csv("C:\hackathon_projects\data\predictive_layer_with_level.csv")

df["predicted_risk_score"] = df["predicted_risk_score"].fillna(0)

df["simulated_risk_score"] = df["predicted_risk_score"] * 1.2
df["simulated_risk_score"] = df["simulated_risk_score"].clip(0, 100)

low_threshold = df["simulated_risk_score"].quantile(0.33)
high_threshold = df["simulated_risk_score"].quantile(0.66)

conditions = [
    df["simulated_risk_score"] < low_threshold,
    (df["simulated_risk_score"] >= low_threshold) & (df["simulated_risk_score"] < high_threshold),
    df["simulated_risk_score"] >= high_threshold
]

levels = ["Low", "Medium", "High"]
df["simulated_risk_level"] = np.select(conditions, levels, default="Low")

simulated_high_risk = df[df["simulated_risk_level"] == "High"].sort_values(
    by="simulated_risk_score", ascending=False
)
print("High risk snapshot:")
print(simulated_high_risk[['latitude','longitude','hour_of_day','simulated_risk_score']].head(10))

top_simulated_hotspots = (
    df.groupby(['latitude','longitude'])['simulated_risk_score']
    .mean()
    .reset_index()
    .sort_values(by='simulated_risk_score', ascending=False)
    .head(20)
)
top_simulated_hotspots.to_csv("simulation_mode_hotspots_overall.csv", index=False)

top_hourly_hotspots = (
    df.groupby(['latitude','longitude','hour_of_day'])['simulated_risk_score']
    .mean()
    .reset_index()
    .sort_values(by='simulated_risk_score', ascending=False)
    .head(20)
)
top_hourly_hotspots.to_csv("simulation_mode_hotspots_hourly.csv", index=False)

df["simulated_risk_level"].value_counts()

risk_counts = df["simulated_risk_level"].value_counts()
print("Risk level distribution:\n", risk_counts)

df.to_csv("simulation_mode_full.csv", index=False)

print("Simulation complete. Top hotspots saved to CSV.")