# -*- coding: utf-8 -*-
"""planner_mode.Infrastructure_Planning_Suggestions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1un_6aJKBkR6CtldMCNpem5YOl1qv_ycY
"""

import pandas as pd

df = pd.read_csv("C:\hackathon_projects\data\predictive_layer_with_level.csv")

def infrastructure_suggestion(row):
    if row["predicted_risk_score"] > 60:
        return "High priority: Review infrastructure"
    elif row["predicted_risk_score"] > 40:
        return "Medium priority: Monitor and repair"
    else:
        return "Low priority: Infrastructure adequate"

# Apply the function
df["infra_recommendation"] = df.apply(infrastructure_suggestion, axis=1)

danger_zones = df[df['predicted_risk_level_balanced'] == 'High']