# -*- coding: utf-8 -*-
"""planner_mode.risk_hotspot_detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QLsFj0oyy1LCwnkrRixeIOzJZC3P33nK
"""

import pandas as pd

df=pd.read_csv("C:\hackathon_projects\data\predictive_layer_with_level.csv")

df.head()

df.columns

def risk_level(score):
    if score > 70:
        return 'High'
    elif score > 50:
        return 'Medium'
    else:
        return 'Low'

df['predicted_risk_level'] = df['predicted_risk_score'].apply(risk_level)

top_hotspots = df.sort_values(by="predicted_risk_score", ascending=False).head(10)
print("Top 10 Hotspots:")
print(top_hotspots[['latitude', 'longitude', 'predicted_risk_score', 'predicted_risk_level']])

danger_zones = df[df['predicted_risk_score'] > 60]
print("\nDanger Zones:")
print(danger_zones[['latitude', 'longitude', 'predicted_risk_score', 'predicted_risk_level']])

df['risk_quartile'] = pd.qcut(df['predicted_risk_score'],
                              q=3,
                              labels=['Q1_Low', 'Q2_Medium', 'Q3_High'])

quartile_to_level = {
    'Q1_Low': 'Low',
    'Q2_Medium': 'Medium',
    'Q3_High': 'High',
}

df['predicted_risk_level_balanced'] = df['risk_quartile'].map(quartile_to_level)

print(df['predicted_risk_level_balanced'].value_counts())

danger_zones.to_csv("planner_hotspots.csv", index=False)