# -*- coding: utf-8 -*-
"""planner_mode.Micromobility_Lane_Planning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHKlZcIYPFRlldi9bnTD6X0H0sZ_TsMY
"""

import pandas as pd

df=pd.read_csv("C:\hackathon_projects\data\predictive_layer_with_level.csv")

micromobility_risk_zones = df[df["predicted_risk_level"] == "High"]

micromobility_risk_zones[['latitude','longitude','hour_of_day','predicted_risk_score']]

severe_micromobility_risk = df[df["predicted_risk_score"] > 70]

severe_micromobility_risk[['latitude','longitude','predicted_risk_score']]

lane_planning_locations = (
    severe_micromobility_risk
    .groupby(['latitude','longitude'])['predicted_risk_score']
    .mean()
    .reset_index()
)

lane_planning_locations = lane_planning_locations.sort_values(
    by="predicted_risk_score",
    ascending=False
)

top_lane_planning_locations = lane_planning_locations.head(30)

top_lane_planning_locations

top_lane_planning_locations.to_csv(
    "micromobility_lane_planning_locations.csv",
    index=False
)

df.to_csv("planner_infrastructure_recommendations.csv", index=False)