# -*- coding: utf-8 -*-
"""planner_mode.Emergency_Infrastructure_Planning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15t38IPpBEExZhWMso94MpF9H6XaMtgkN
"""

import pandas as pd
import numpy as np

df=pd.read_csv("C:\hackathon_projects\data\predictive_layer_with_level.csv")

df.columns

critical_zones = df[df["predicted_risk_score"] > 75]

critical_zones[['latitude','longitude','hour_of_day','predicted_risk_score']]

emergency_priority = df[df["predicted_risk_level"] == "High"]

emergency_priority[['latitude','longitude','hour_of_day','predicted_risk_score']]

safe_corridors = df[df["predicted_risk_level"] == "Low"]

safe_corridors[['latitude','longitude','predicted_risk_score']]

top_emergency_locations = (
    df.groupby(['latitude','longitude'])['predicted_risk_score']
    .mean()
    .reset_index()
    .sort_values(by='predicted_risk_score', ascending=False)
    .head(20)
)

top_emergency_locations

critical_zones.to_csv("critical_emergency_zones.csv", index=False)

emergency_priority.to_csv("emergency_priority_zones.csv", index=False)

safe_corridors.to_csv("safe_emergency_corridors.csv", index=False)

top_emergency_locations.to_csv("top_emergency_locations.csv", index=False)

