# -*- coding: utf-8 -*-
"""predictive_layer_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eyc286AcNphMhg0gOIT_LXjohkY8T8iu
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

df=pd.read_csv("C:\hackathon_projects\data\risk_with_time_filter.csv")

print(df.columns)

features = [
    # Traffic & mobility
    "traffic_density", "vehicle_density", "avg_vehicle_speed",
    "heavy_vehicle_ratio", "two_wheeler_ratio", "delivery_vehicle_density",
    "micro_mobility_usage", "e_rickshaw_density", "num_lanes", "intersection_density",

    # Infrastructure & compliance
    "pothole_density", "road_quality", "footpath_quality", "encroachment_level",
    "street_light", "traffic_signal", "pedestrian_crossing",
    "speed_violation_rate", "wrong_side_driving_rate", "helmet_usage_rate",

    # Weather & visibility
    "visibility", "temperature", "rainfall", "wind_speed",
    "weather_condition_fog", "weather_condition_haze", "weather_condition_rain",

    # Temporal
    "hour_of_day", "festival_day",
    "day_of_week_Mon", "day_of_week_Tue", "day_of_week_Wed",
    "day_of_week_Thu", "day_of_week_Sat", "day_of_week_Sun",

    # Zones & road type
    "zone_East Delhi", "zone_New Delhi", "zone_North Delhi", "zone_North East Delhi",
    "zone_North West Delhi", "zone_Shahdara", "zone_South Delhi",
    "zone_South West Delhi", "zone_West Delhi",
    "road_type_highway", "road_type_market_road", "road_type_residential",
    "road_type_service_road",

    # Time-based risk
    "time_risk_score"
]
target = "risk_score"  # Predict the overall risk score

X = df[features]
y = df[target]
df[features]

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

rf = RandomForestRegressor(random_state=42)

param_grid = {
    "n_estimators": [100, 150, 200],
    "max_depth": [5, 10, 15, None],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2],
    "max_features": ["sqrt", "log2", None]
}

search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_grid,
    n_iter=10,  # number of random combinations
    scoring="neg_mean_squared_error",
    cv=3,
    verbose=2,
    random_state=42,
    n_jobs=-1
)

search.fit(X_train, y_train)

best_rf = search.best_estimator_
print("Best hyperparameters:", search.best_params_)

y_pred = best_rf.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"Predictive Layer RMSE (tuned): {rmse:.4f}")

df_pred = df.copy()

predicted_scores = []

# Loop over all hours in a day (0-23)
for hour in range(24):
    temp_df = df_pred.copy()
    temp_df['hour_of_day'] = hour

    # Update day_of_week columns if needed (here keeping them same as original)

    # Scale features
    X_temp_scaled = scaler.transform(temp_df[features])

    # Predict risk score
    temp_df['predicted_risk_score'] = best_rf.predict(X_temp_scaled)

    predicted_scores.append(temp_df[['latitude', 'longitude', 'hour_of_day', 'predicted_risk_score']])

predictive_layer_df = pd.concat(predicted_scores, ignore_index=True)

low_thresh = predictive_layer_df['predicted_risk_score'].quantile(0.33)
high_thresh = predictive_layer_df['predicted_risk_score'].quantile(0.66)

def classify_risk(score):
    if score <= low_thresh:
        return 'Low'
    elif score <= high_thresh:
        return 'Medium'
    else:
        return 'High'

predictive_layer_df['predicted_risk_level'] = predictive_layer_df['predicted_risk_score'].apply(classify_risk)
predictive_layer_df.to_csv("predictive_layer_with_level.csv", index=False)

predictive_layer_df['predicted_risk_level'].value_counts()