# -*- coding: utf-8 -*-
"""Risk_scoring_engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C758Onz7UVf3MJ-Hc0faBG2gmxYLpvlO
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
import numpy as np

df=pd.read_csv("C:\Users\NEW\Downloads\balanced_risk_dataset.csv")

sns.countplot(x="risk_level", data=df)
plt.show()

df.isnull().sum()

df.columns

df.shape

features = [
    # Traffic & mobility
    "traffic_density", "vehicle_density", "avg_vehicle_speed",
    "heavy_vehicle_ratio", "two_wheeler_ratio", "delivery_vehicle_density",
    "micro_mobility_usage", "e_rickshaw_density", "num_lanes", "intersection_density",

    # Road infrastructure & compliance
    "pothole_density", "road_quality", "footpath_quality", "encroachment_level",
    "street_light", "traffic_signal", "pedestrian_crossing",
    "speed_violation_rate", "wrong_side_driving_rate", "helmet_usage_rate",

    # Weather & visibility
    "visibility", "temperature", "rainfall", "wind_speed",
    "weather_condition_fog", "weather_condition_haze", "weather_condition_rain",

    # Temporal
    "hour_of_day", "festival_day",
    "day_of_week_Mon", "day_of_week_Sat", "day_of_week_Sun",
    "day_of_week_Thu", "day_of_week_Tue", "day_of_week_Wed",

    # Zones & road type
    "zone_East Delhi", "zone_New Delhi", "zone_North Delhi", "zone_North East Delhi",
    "zone_North West Delhi", "zone_Shahdara", "zone_South Delhi",
    "zone_South West Delhi", "zone_West Delhi",
    "road_type_highway", "road_type_market_road", "road_type_residential",
    "road_type_service_road"
]
features

target = "accident_probability"
X = df[features]
y = df[target]

#Normalize features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Step 4: Split dataset into train/test
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

rf = RandomForestRegressor(random_state=42)

param_grid = {
    "n_estimators": [50, 100, 200],
    "max_depth": [5, 10, 15, None],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2],
    "max_features": ["sqrt", "log2", None]
}
param_grid

search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_grid,
    n_iter=10,
    scoring="neg_mean_squared_error",
    cv=3,
    verbose=2,
    random_state=42,
    n_jobs=-1
)

search.fit(X_train, y_train)

best_rf = search.best_estimator_
print("Best hyperparameters:", search.best_params_)

y_pred = best_rf.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"Test RMSE: {rmse:.4f}")

df["risk_score"] = best_rf.predict(X_scaled) * 100
df["risk_score"]

low_thresh = df["risk_score"].quantile(0.33)
high_thresh = df["risk_score"].quantile(0.66)

def classify_risk(score):
    if score <= low_thresh:
        return "Low"
    elif score <= high_thresh:
        return "Medium"
    else:
        return "High"

df["risk_level"] = df["risk_score"].apply(classify_risk)
df["risk_level"]

print(df["risk_level"].value_counts())

df.to_csv("risk_scored.csv", index=False)
print("Risk scoring with accident history complete!")

