# -*- coding: utf-8 -*-
"""time_based_risk

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18pgMrwF_h9q5wYRpEnGEI43-E57i5QCW
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("C:\hackathon_projects\data\risk_scored.csv")

sns.countplot(x="risk_level", data=df)
plt.show()

df.columns

hourly_risk = df.groupby("hour_of_day")["risk_score"].mean().to_dict()
hourly_risk

day_columns = [
    "day_of_week_Mon","day_of_week_Tue","day_of_week_Wed",
    "day_of_week_Thu","day_of_week_Sat","day_of_week_Sun"
]

df["day_name"] = df[day_columns].idxmax(axis=1).str.replace("day_of_week_", "")
df["day_name"]

hourly_risk = df.groupby("hour_of_day")["risk_score"].mean().to_dict()

daily_risk = df.groupby("day_name")["risk_score"].mean().to_dict()

def time_adjusted_risk(row):
    base = row["risk_score"]
    hour_factor = hourly_risk[row["hour_of_day"]] / df["risk_score"].mean()
    day_factor = daily_risk[row["day_name"]] / df["risk_score"].mean()

    adjusted = base * (hour_factor + day_factor) / 2
    return adjusted

df["time_risk_score"] = df.apply(time_adjusted_risk, axis=1)
df["time_risk_score"]

low_thresh = df["time_risk_score"].quantile(0.33)
high_thresh = df["time_risk_score"].quantile(0.66)

def classify_time_risk(score):
    if score <= low_thresh:
        return "Low"
    elif score <= high_thresh:
        return "Medium"
    else:
        return "High"

df["time_risk_level"] = df["time_risk_score"].apply(classify_time_risk)
df["time_risk_level"]

print(df["time_risk_level"].value_counts())

df.to_csv("risk_with_time_filter.csv", index=False)
print("Time-based risk filter applied successfully!")



